# Generated by Django 3.1.5 on 2021-01-16 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=254)),
                ('task_complete', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
